table Dim_Departure
	lineageTag: 5d4b8f24-0f7a-400f-81d2-42f120d0fd5e

	column Dapature_Station_ID
		dataType: string
		lineageTag: 526a6ffd-ee0c-41d6-a34a-cc2cb67df86b
		summarizeBy: none
		sourceColumn: Dapature_Station_ID

		annotation SummarizationSetBy = Automatic

	column 'Departure Station'
		dataType: string
		lineageTag: d373a463-b522-42ed-a181-e89ccaac5467
		summarizeBy: none
		sourceColumn: Departure Station

		annotation SummarizationSetBy = Automatic

	partition Dim_Departure = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data_Analytics\Datasets\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Departure Station"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Index",{{"Index", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Index", "Dapature_Station_ID"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Dapature_Station_ID", "Departure Station"}),
				    #"Added Prefix" = Table.TransformColumns(#"Reordered Columns", {{"Dapature_Station_ID", each "DEP" & _, type text}})
				in
				    #"Added Prefix"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

