table Dim_Delay
	lineageTag: bf2f5251-4e61-4999-9b44-50601ae7303a

	column Delay_ID
		dataType: string
		lineageTag: 00077a74-f7d6-4e3d-9f12-4d6e3be231ca
		summarizeBy: none
		sourceColumn: Delay_ID

		annotation SummarizationSetBy = Automatic

	column 'Reason for Delay'
		dataType: string
		lineageTag: e91826a0-0f32-40c6-8675-f881861a9955
		summarizeBy: none
		sourceColumn: Reason for Delay

		annotation SummarizationSetBy = Automatic

	partition Dim_Delay = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data_Analytics\Datasets\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Reason for Delay"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Other Columns","Signal failure","Signal Failure",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Staff Shortage","Staffing",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Weather Conditions","Weather",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Value2"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Reason for Delay"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Delay_ID"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Delay_ID", type text}}),
				    #"Added Prefix" = Table.TransformColumns(#"Changed Type1", {{"Delay_ID", each "DEL" & _, type text}}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Added Prefix","","None",Replacer.ReplaceValue,{"Reason for Delay"})
				in
				    #"Replaced Value3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

