table Dim_Purchase
	lineageTag: 14b87f61-9852-4a27-884d-899984875513

	column Purchase_ID
		dataType: string
		lineageTag: 12f85013-cb6b-4545-9d8e-78e858f24460
		summarizeBy: none
		sourceColumn: Purchase_ID

		annotation SummarizationSetBy = Automatic

	column 'Purchase Type'
		dataType: string
		lineageTag: d9cf89e8-a4fa-4ffd-b8a5-78a47e7d7bb7
		summarizeBy: none
		sourceColumn: Purchase Type

		annotation SummarizationSetBy = Automatic

	partition Dim_Purchase = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data_Analytics\Datasets\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Purchase Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Purchase Type"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Index", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Index", "Purchase_ID"}}),
				    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Purchase_ID", each "PUR" & _, type text}})
				in
				    #"Added Prefix"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

