table Dim_Railcard
	lineageTag: 00478045-d603-4046-92b1-5f38e959a9a2

	column Railcard_ID
		dataType: string
		lineageTag: d9962663-c7d8-452d-aa78-8b1218469ce9
		summarizeBy: none
		sourceColumn: Railcard_ID

		annotation SummarizationSetBy = Automatic

	column Railcard
		dataType: string
		lineageTag: 996f23f1-6c51-41cf-897a-aa1ec73cb04c
		summarizeBy: none
		sourceColumn: Railcard

		annotation SummarizationSetBy = Automatic

	column Railcard_Holder
		dataType: string
		lineageTag: 21c28b90-dd6f-40c2-bdd6-f3c4eca752c4
		summarizeBy: none
		sourceColumn: Railcard_Holder

		annotation SummarizationSetBy = Automatic

	partition Dim_Railcard = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data_Analytics\Datasets\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Railcard"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Railcard"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Index", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Index", "Railcard_ID"}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Renamed Columns", "Custom", each if [Railcard] = "None" then "Non-Holder" else "Holder"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Custom", "Railcard_Holder"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Railcard_Holder", type text}}),
				    #"Added Prefix" = Table.TransformColumns(#"Changed Type2", {{"Railcard_ID", each "RAIL" & _, type text}})
				in
				    #"Added Prefix"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

