table Dim_Ticket
	lineageTag: cbaa3f59-b1ae-4911-8d61-9ad66883baf3

	column Ticket_ID
		dataType: string
		lineageTag: f7f41cfa-b968-458d-b401-3e9c80f3666f
		summarizeBy: none
		sourceColumn: Ticket_ID

		annotation SummarizationSetBy = Automatic

	column 'Ticket Class'
		dataType: string
		lineageTag: 681fb578-4055-41cb-a977-f97f3c44d7ac
		summarizeBy: none
		sourceColumn: Ticket Class

		annotation SummarizationSetBy = Automatic

	column 'Ticket Type'
		dataType: string
		lineageTag: 8e7f071c-da80-4083-9d14-771086313ba4
		summarizeBy: none
		sourceColumn: Ticket Type

		annotation SummarizationSetBy = Automatic

	partition Dim_Ticket = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Data_Analytics\Datasets\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Ticket Class", "Ticket Type"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Ticket Class", "Ticket Type"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Index", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Index", "Ticket_ID"}}),
				    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Ticket_ID", each "TKT" & _, type text}})
				in
				    #"Added Prefix"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

