table Fact_Transaction
	lineageTag: df417e1c-8ae5-4075-b124-7e19c3128430

	column Transaction_ID
		dataType: string
		lineageTag: 8ef5f93c-3ebd-4a81-aa71-8e1a43024e42
		summarizeBy: none
		sourceColumn: Transaction_ID

		annotation SummarizationSetBy = Automatic

	column 'Date of Purchase'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06fd898e-ac33-41d6-a184-5840ec05df71
		summarizeBy: none
		sourceColumn: Date of Purchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Time of Purchase'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a2cb6c5b-1839-409e-92a1-1b3fb0b81398
		summarizeBy: none
		sourceColumn: Time of Purchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Price
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3bcd664f-2103-4637-b254-b514654b76ee
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Date of Journey'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 327c9cc1-6c65-4688-82e4-5128ca900c06
		summarizeBy: none
		sourceColumn: Date of Journey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Departure Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3d75bdab-a8b6-4fd8-ae1f-e6d795c9295c
		summarizeBy: none
		sourceColumn: Departure Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Arrival Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: c2673812-d0b5-4fdf-b951-315a7cca01ee
		summarizeBy: none
		sourceColumn: Arrival Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Actual Arrival Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: cd48caf1-70ec-457a-aa40-fae07d15b415
		summarizeBy: none
		sourceColumn: Actual Arrival Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Refund Request'
		dataType: string
		lineageTag: 6558cc61-c62a-4ef8-897a-afb0fb862710
		summarizeBy: none
		sourceColumn: Refund Request

		annotation SummarizationSetBy = Automatic

	column Purchase_ID
		dataType: string
		lineageTag: 4b28e413-0177-4890-be13-e50833580229
		summarizeBy: none
		sourceColumn: Purchase_ID

		annotation SummarizationSetBy = Automatic

	column Payment_ID
		dataType: string
		lineageTag: 50fa67e5-e88a-4394-a24f-3e25de94f781
		summarizeBy: none
		sourceColumn: Payment_ID

		annotation SummarizationSetBy = Automatic

	column Railcard_ID
		dataType: string
		lineageTag: 8f33c4c4-9bda-410d-bca2-b277531652d9
		summarizeBy: none
		sourceColumn: Railcard_ID

		annotation SummarizationSetBy = Automatic

	column Dapature_Station_ID
		dataType: string
		lineageTag: 1cdf252f-f341-46e9-9721-001f8ba3e11c
		summarizeBy: none
		sourceColumn: Dapature_Station_ID

		annotation SummarizationSetBy = Automatic

	column Arrival_ID
		dataType: string
		lineageTag: 8e04acbf-ebd2-48f5-a43c-8c3d5293661d
		summarizeBy: none
		sourceColumn: Arrival_ID

		annotation SummarizationSetBy = Automatic

	column Delay_ID
		dataType: string
		lineageTag: 65468486-c351-475f-b39b-f7c100a6724c
		summarizeBy: none
		sourceColumn: Delay_ID

		annotation SummarizationSetBy = Automatic

	column Status_ID
		dataType: string
		lineageTag: ed39adda-238d-4a1b-a459-ea45d69e71a5
		summarizeBy: none
		sourceColumn: Status_ID

		annotation SummarizationSetBy = Automatic

	column Ticket_ID
		dataType: string
		lineageTag: 13ceeb64-b809-465d-87c6-576d59ceb806
		summarizeBy: none
		sourceColumn: Ticket_ID

		annotation SummarizationSetBy = Automatic

	partition Fact_Transaction = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Mohab\DEPI\project\UK Train Rides\railway.csv"),[Delimiter=",", Columns=18, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Transaction ID", type text}, {"Date of Purchase", type date}, {"Time of Purchase", type time}, {"Purchase Type", type text}, {"Payment Method", type text}, {"Railcard", type text}, {"Ticket Class", type text}, {"Ticket Type", type text}, {"Price", Int64.Type}, {"Departure Station", type text}, {"Arrival Destination", type text}, {"Date of Journey", type date}, {"Departure Time", type time}, {"Arrival Time", type time}, {"Actual Arrival Time", type time}, {"Journey Status", type text}, {"Reason for Delay", type text}, {"Refund Request", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Transaction ID"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Columns", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Transaction_ID"}}),
				    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Transaction_ID", each "TRIP" & Text.From(_, "en-US"), type text}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Prefix",{"Transaction_ID", "Date of Purchase", "Time of Purchase", "Purchase Type", "Payment Method", "Railcard", "Ticket Class", "Ticket Type", "Price", "Departure Station", "Arrival Destination", "Date of Journey", "Departure Time", "Arrival Time", "Actual Arrival Time", "Journey Status", "Reason for Delay", "Refund Request"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Transaction_ID", type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"Purchase Type"}, Dim_Purchase, {"Purchase Type"}, "Dim_Purchase", JoinKind.LeftOuter),
				    #"Expanded Dim_Purchase" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Purchase", {"Purchase_ID"}, {"Purchase_ID"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Dim_Purchase",{"Purchase Type"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns1", {"Payment Method"}, Dim_Payment, {"Payment Method"}, "Dim_Payment", JoinKind.LeftOuter),
				    #"Expanded Dim_Payment" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_Payment", {"Payment_ID"}, {"Payment_ID"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded Dim_Payment",{"Payment Method"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Columns2", {"Railcard"}, Dim_Railcard, {"Railcard"}, "Dim_Railcard", JoinKind.LeftOuter),
				    #"Expanded Dim_Railcard" = Table.ExpandTableColumn(#"Merged Queries2", "Dim_Railcard", {"Railcard_ID"}, {"Railcard_ID"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Expanded Dim_Railcard",{"Railcard"}),
				    #"Merged Queries3" = Table.NestedJoin(#"Removed Columns3", {"Ticket Class"}, Dim_Ticket, {"Ticket Class"}, "Dim_Ticket", JoinKind.LeftOuter),
				    #"Expanded Dim_Ticket" = Table.ExpandTableColumn(#"Merged Queries3", "Dim_Ticket", {"Ticket_ID"}, {"Ticket_ID"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded Dim_Ticket", {"Departure Station"}, Dim_Departure, {"Departure Station"}, "Dim_Departure", JoinKind.LeftOuter),
				    #"Expanded Dim_Departure" = Table.ExpandTableColumn(#"Merged Queries4", "Dim_Departure", {"Dapature_Station_ID"}, {"Dapature_Station_ID"}),
				    #"Removed Columns5" = Table.RemoveColumns(#"Expanded Dim_Departure",{"Departure Station"}),
				    #"Merged Queries5" = Table.NestedJoin(#"Removed Columns5", {"Arrival Destination"}, Dim_Arrival, {"Arrival Destination"}, "Dim_Arrival", JoinKind.LeftOuter),
				    #"Expanded Dim_Arrival" = Table.ExpandTableColumn(#"Merged Queries5", "Dim_Arrival", {"Arrival_ID"}, {"Arrival_ID"}),
				    #"Removed Columns6" = Table.RemoveColumns(#"Expanded Dim_Arrival",{"Arrival Destination"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns6","Signal failure","Signal Failure",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Staff Shortage","Staffing",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Weather Conditions","Weather",Replacer.ReplaceText,{"Reason for Delay"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Replaced Value2", {"Reason for Delay"}, Dim_Delay, {"Reason for Delay"}, "Dim_Delay", JoinKind.LeftOuter),
				    #"Expanded Dim_Delay" = Table.ExpandTableColumn(#"Merged Queries6", "Dim_Delay", {"Delay_ID"}, {"Delay_ID"}),
				    #"Removed Columns7" = Table.RemoveColumns(#"Expanded Dim_Delay",{"Reason for Delay"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Removed Columns7",null,"",Replacer.ReplaceValue,{"Delay_ID"}),
				    #"Merged Queries7" = Table.NestedJoin(#"Replaced Value3", {"Journey Status"}, Dim_Status, {"Journey Status"}, "Dim_Status", JoinKind.LeftOuter),
				    #"Expanded Dim_Status" = Table.ExpandTableColumn(#"Merged Queries7", "Dim_Status", {"Status_ID"}, {"Status_ID"}),
				    #"Removed Columns8" = Table.RemoveColumns(#"Expanded Dim_Status",{"Journey Status"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns8",{{"Price", Currency.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type2", {"Transaction_ID"}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Removed Duplicates",{"Ticket Class", "Ticket Type"})
				in
				    #"Removed Columns4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

