table 'Financial Measures'
	lineageTag: 77fc8b29-84dd-47df-979c-a0dec0f5c1c3

	measure 'Measure 5' = ""
		lineageTag: fca64fe2-7769-444e-b092-ba7c9d5cecf1

	partition 'Financial Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

