table 'Hero Station Measures'
	lineageTag: ab5b8dad-e298-40f2-b55c-3e5ed08b2c8e

	measure 'Total Revenue Combined' = SUM('Station Revenue Combined'[Revenue])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 54a54fc1-48f4-4afa-be90-d0983889401e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Top Station Name' =
			
			CALCULATE(
			    SELECTEDVALUE('Station Revenue Combined'[Station]),
			    TOPN(1, ALL('Station Revenue Combined'[Station]), [Total Revenue Combined], DESC)
			)
		lineageTag: adb4a691-1791-422c-be38-fabd3ad1e91e

	measure 'Is Hero Station' =
			
			IF(
			    SELECTEDVALUE('Station Revenue Combined'[Station]) = [Top Station Name],
			    1, 0
			)
		formatString: 0
		lineageTag: a4e417fb-13be-40a2-b3d9-5d323ade5688

	measure 'Hero Station' = ```
			
			VAR _TopStation =
			    TOPN(
			        1,
			        SUMMARIZE(
			            'Station Revenue Combined',
			            'Station Revenue Combined'[Station],
			            "TotalRevenue", [Total Revenue Combined]
			        ),
			        [Total Revenue Combined],
			        DESC
			    )
			RETURN
			MAXX(_TopStation, 'Station Revenue Combined'[Station])
			
			```
		lineageTag: e87eb985-0126-4e73-83d2-1d7d08c89e7d

	measure 'Hero Station Total Revenue' = ```
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    SUM(fact_Transaction[Price]),
			    FILTER(
			        fact_Transaction,
			        RELATED(dim_departure[Departure Station]) = _Hero
			        || RELATED(dim_arrival[Arrival Destination]) = _Hero
			    )
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 9ec61b87-27ab-47d5-916a-63466f5840cf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Hero Station Total Passengers' = ```
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    COUNTROWS(fact_Transaction),
			    FILTER(
			        fact_Transaction,
			        RELATED(dim_departure[Departure Station]) = _Hero
			            || RELATED(Dim_Arrival[Arrival Destination]) = _Hero
			    )
			)
			
			```
		formatString: 0
		lineageTag: dc170216-0919-48b6-83c6-0bac0665524a

	measure 'Hero Station On-Time %' = ```
			
			VAR _Hero = [Hero Station]
			VAR _Total =
			    CALCULATE(
			        COUNTROWS(fact_Transaction),
			        FILTER(
			            fact_Transaction,
			            RELATED(dim_departure[Departure Station]) = _Hero
			                || RELATED(Dim_Arrival[Arrival Destination]) = _Hero
			        )
			    )
			VAR _OnTime =
			    CALCULATE(
			        COUNTROWS(fact_Transaction),
			        FILTER(
			            fact_Transaction,
			            RELATED(Dim_Status[Journey Status]) = "On Time"
			                && (
			                    RELATED(dim_departure[Departure Station]) = _Hero
			                    || RELATED(Dim_Arrival[Arrival Destination]) = _Hero
			                )
			        )
			    )
			RETURN
			DIVIDE(_OnTime, _Total)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 23fa61ab-3518-407c-9099-1232f2117aae

	measure 'Hero Station Refund %' = ```
			
			VAR _Hero = [Hero Station]
			VAR _Total =
			    CALCULATE(
			        COUNTROWS(fact_Transaction),
			        FILTER(
			            fact_Transaction,
			            RELATED(dim_departure[Departure Station]) = _Hero
			                || RELATED(Dim_Arrival[Arrival Destination]) = _Hero
			        )
			    )
			VAR _Refunds =
			    CALCULATE(
			        COUNTROWS(fact_Transaction),
			        FILTER(
			            fact_Transaction,
			            fact_Transaction[Refund Request] = "Yes"
			                && (
			                    RELATED(dim_departure[Departure Station]) = _Hero
			                    || RELATED(Dim_Arrival[Arrival Destination]) = _Hero
			                )
			        )
			    )
			RETURN
			DIVIDE(_Refunds, _Total)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bfb96709-ac09-4545-afa4-199bb0910cef

	measure 'Hero Revenue Over Time' = ```
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    SUM(fact_Transaction[Price]),
			    FILTER(
			        fact_Transaction,
			        RELATED(dim_departure[Departure Station]) = _Hero
			          || RELATED(dim_arrival[Arrival Destination]) = _Hero
			    )
			)
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7ad92d81-1408-4aa2-a3fd-e93135c1793d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Hero Passengers Over Time' = ```
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    COUNTROWS(fact_Transaction),
			    FILTER(
			        fact_Transaction,
			        RELATED(dim_departure[Departure Station]) = _Hero
			          || RELATED(dim_arrival[Arrival Destination]) = _Hero
			    )
			)
			
			```
		formatString: 0
		lineageTag: 284b2133-732f-4e48-aaf0-1b6165c4dc91

	measure 'Hero Ticket Count' = ```
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    COUNTROWS(fact_Transaction),
			    FILTER(
			        fact_Transaction,
			        RELATED(Dim_Ticket[Ticket Class]) <> BLANK()
			          && (RELATED(dim_departure[Departure Station]) = _Hero
			              || RELATED(dim_arrival[Arrival Destination]) = _Hero)
			    )
			)
			
			```
		formatString: 0
		lineageTag: a625d449-dc6a-4475-a5b6-56074655956e

	measure 'Hero Delay Count' =
			
			VAR _Hero = [Hero Station]
			RETURN
			CALCULATE(
			    COUNTROWS(fact_Transaction),
			    FILTER(
			        fact_Transaction,
			        NOT(ISBLANK(fact_Transaction[Delay_ID]))
			          && (RELATED(dim_departure[Departure Station]) = _Hero
			              || RELATED(dim_arrival[Arrival Destination]) = _Hero)
			    )
			)
		formatString: 0
		lineageTag: af238d77-2301-4b5e-8028-367fbed07ff6

	measure 'Hero Station Payment Count' =
			
			CALCULATE(
			    COUNTROWS(Fact_Transaction),
			    FILTER(
			        Fact_Transaction,
			        RELATED(dim_departure[Departure Station]) = [Hero Station]
			        || RELATED(dim_arrival[Arrival Destination]) = [Hero Station]
			    )
			)
		formatString: 0
		lineageTag: 5d422c59-5024-4d54-b923-59767537bfe9

	partition 'Hero Station Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

