table 'Hero Station Measures'
	lineageTag: ab5b8dad-e298-40f2-b55c-3e5ed08b2c8e

	measure 'Measure 6' = ""
		lineageTag: 54a54fc1-48f4-4afa-be90-d0983889401e

	partition 'Hero Station Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

