table 'Station Measures'
	lineageTag: 678d8d9b-ce1f-4d7c-88cc-6f44d9909fa8

	measure 'Measure 2' = ""
		lineageTag: 93e632b9-e047-44bf-8f96-534c0aa294b6

	partition 'Station Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

